# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-xec-dex:
    image: mongo:4.2.0
    container_name: mongo-xec-dex
    ports:
      - '5666:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-xec-dex:
    # https://github.com/christroutner/trickle-ipfs
    image: christroutner/trickle-ipfs:v1.0.2
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    container_name: ipfs-xec-dex
    environment:
      IPFS_DAEMON_ARGUMENTS: '--enable-pubsub-experiment --migrate=true --agent-version-suffix=docker --routing=dhtclient --enable-gc'
      UPLOAD_KBPS: '1000'
      DOWNLOAD_KBPS: '1000'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 2000mb
    ports:
      - 4001:4001
      - 4003:4003
      - 172.17.0.1:5001:5001
      - 172.17.0.1:8080:8080
    command: [
      './start-ipfs.sh'
    ]
    volumes:
      - ../data/go-ipfs/data:/root/.ipfs
      - ./ipfs/start-ipfs.sh:/root/start-ipfs.sh
    restart: always

  p2wdb-xec-dex:
    build:
      context: ./p2wdb/
      dockerfile: Dockerfile
    #image: christroutner/p2wdb:v3.1.8
    container_name: p2wdb-xec-dex
    environment:
      CONSUMER_URL: 'https://xec-consumer-or1-usa.fullstackcash.nl'
      DEBUG_LEVEL: 1
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1gb
    links:
      - mongo-xec-dex
      - ipfs-xec-dex
    ports:
      # <host port>:<container port>
      - 5667:5667 # REST API
      #- 5668:5668 # IPFS TCP port
      #- 5669:5669 # IPFS WS Port
    volumes:
      - ../data/ipfsdata/p2wdb:/home/safeuser/ecash-p2wdb-service/.ipfsdata/p2wdb
      - ./p2wdb/start-production.sh:/home/safeuser/ecash-p2wdb-service/start-production.sh
    restart: always

  xec-dex:
    build:
      context: ./xec-dex/
      dockerfile: Dockerfile
    #image: christroutner/bch-dex:v2.0.8
    container_name: xec-dex
    environment:
      CONSUMER_URL: 'https://xec-consumer-or1-usa.fullstackcash.nl'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1000mb
    links:
      - mongo-xec-dex
      - p2wdb-xec-dex
    ports:
      - '5700:5700' # <host port>:<container port>
    volumes:
      - ../scripts/wallet.json:/home/safeuser/xec-dex/wallet.json
      - ./xec-dex/start-production.sh:/home/safeuser/xec-dex/start-production.sh
    restart: always

  xec-dex-ui:
    build:
      context: ./xec-dex-ui/
      dockerfile: Dockerfile
    #image: christroutner/bch-dex-ui:v1.2.4
    container_name: xec-dex-ui
    environment:
      REACT_APP_SERVER: 'http://192.168.2.3'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 500mb
    links:
      - xec-dex
    ports:
      - '4500:80' # <host port>:<container port>
    # volumes:
    #   - ../data/ipfsdata:/home/safeuser/ipfs-service-provider/.ipfsdata
    restart: always
